/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import kontroler.Kontroler;
import form.util.FormIzbor;
import domain.Klijent;
import domain.VlasnikSmestaja;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nit.Osluskivac;
import sesija.Sesija;

/**
 *
 * @author user
 */
public class FormLogin extends javax.swing.JFrame {

    FormMain frm;
    
    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setRadioButtons();
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("\\icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupa = new javax.swing.ButtonGroup();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblRegistracija = new javax.swing.JLabel();
        lblHyperlink = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pnlUloga = new javax.swing.JPanel();
        btnKlijent = new javax.swing.JRadioButton();
        btnVlasnik = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BuKing - Login forma");
        setResizable(false);

        lblUsername.setText("Username: ");

        jLabel1.setText("Password: ");

        lblRegistracija.setText("Nemate nalog? Registrujte se");

        lblHyperlink.setForeground(new java.awt.Color(51, 102, 255));
        lblHyperlink.setText("ovde.");
        lblHyperlink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHyperlinkMouseClicked(evt);
            }
        });

        btnLogin.setText("Prijavi se");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        pnlUloga.setBorder(javax.swing.BorderFactory.createTitledBorder("Prijavljujem se kao"));

        btnKlijent.setText("Klijent");

        btnVlasnik.setText("Vlasnik smeštaja");

        javax.swing.GroupLayout pnlUlogaLayout = new javax.swing.GroupLayout(pnlUloga);
        pnlUloga.setLayout(pnlUlogaLayout);
        pnlUlogaLayout.setHorizontalGroup(
            pnlUlogaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUlogaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKlijent)
                .addGap(55, 55, 55)
                .addComponent(btnVlasnik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUlogaLayout.setVerticalGroup(
            pnlUlogaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUlogaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUlogaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKlijent)
                    .addComponent(btnVlasnik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRegistracija)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHyperlink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                    .addComponent(pnlUloga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(pnlUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistracija)
                    .addComponent(lblHyperlink)
                    .addComponent(btnLogin))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHyperlinkMouseClicked
        FormIzbor frm = new FormIzbor(this, true);
        frm.setVisible(true);
        /*FormRegistracija frm = new FormRegistracija();
         frm.setVisible(true);
         this.dispose();*/
    }//GEN-LAST:event_lblHyperlinkMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            if (btnKlijent.isSelected()) {
                try {
                    Klijent klijent = Kontroler.getInstance().loginKlijent(username, password);

                    setVisible(false);
                    Sesija.getInstance().setKorisnik(klijent);

                    frm = new FormMain();
                    frm.setVisible(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                try {
                    VlasnikSmestaja vlasnik = Kontroler.getInstance().loginVlasnik(username, password);

                    setVisible(false);
                    Sesija.getInstance().setKorisnik(vlasnik);
                    frm = new FormMain();
                    frm.setVisible(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupa;
    private javax.swing.JRadioButton btnKlijent;
    private javax.swing.JButton btnLogin;
    private javax.swing.JRadioButton btnVlasnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHyperlink;
    private javax.swing.JLabel lblRegistracija;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlUloga;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void setRadioButtons() {
        btnGrupa.add(btnKlijent);
        btnGrupa.add(btnVlasnik);
        btnKlijent.setSelected(true);
    }

    public void ugasi() {
        JOptionPane.showMessageDialog(this, "Server se gasi!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
        if (frm != null) {
            frm.ugasi();
        }
        dispose();
    }
}
