/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.smestaj;

import domain.Smestaj;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author user
 */
public class FormNoviSmestaj extends javax.swing.JDialog {

    /**
     * Creates new form FormNoviSmestaj
     */
    public FormNoviSmestaj(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    public FormNoviSmestaj(java.awt.Dialog parent, boolean modal, Smestaj s) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        onemoguciIPopuni(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCena = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        btnSacuvaj = new javax.swing.JButton();
        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        lblBrojKreveta = new javax.swing.JLabel();
        spinBrojKreveta = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BuKing - Kreiranje smestaja");

        lblCena.setText("Cena prenocista:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opis smestaja"));

        txtOpis.setColumns(20);
        txtOpis.setLineWrap(true);
        txtOpis.setRows(5);
        txtOpis.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtOpis);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSacuvaj.setText("Kreiraj smestaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        lblNaziv.setText("Naziv smestaja:");

        lblBrojKreveta.setText("Broj kreveta: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv)
                    .addComponent(lblBrojKreveta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spinBrojKreveta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lblCena)
                        .addGap(18, 18, 18)
                        .addComponent(txtCena)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojKreveta)
                    .addComponent(spinBrojKreveta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCena)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String naziv = txtNaziv.getText();
        String opis = txtOpis.getText();
        int brKreveta = (Integer) spinBrojKreveta.getValue();
        double cena;
        if (!txtCena.getText().equals("")) {
            cena = Double.parseDouble(txtCena.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            validacija(naziv, opis, brKreveta, cena);
            Smestaj smestaj = Kontroler.getInstance().kreirajSmestaj(naziv, opis, brKreveta, cena);
            
            JOptionPane.showMessageDialog(this.getParent(), "Uspesno ste kreirali smestaj!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojKreveta;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JSpinner spinBrojKreveta;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    // End of variables declaration//GEN-END:variables

    private void validacija(String naziv, String opis, int brKreveta, double cena) throws Exception {
        if (naziv.isEmpty() || opis.isEmpty()) {
            throw new Exception("Sva polja moraju biti popunjena!");
        }
        if(brKreveta < 1){
            throw new Exception("Broj kreveta ne moze biti manji od 1");
        }
        if(cena < 0){
            throw new Exception("Cena smestaja ne moze biti negativna");
        }
    }

    private void onemoguciIPopuni(Smestaj s) {
        txtCena.setEditable(false);
        txtNaziv.setEditable(false);
        txtOpis.setEditable(false);
        spinBrojKreveta.setEnabled(false);
        btnSacuvaj.setVisible(false);
        
        txtNaziv.setText(s.getNazivSmestaja());
        txtCena.setText(s.getCenaPrenocista()+"");
        txtOpis.setText(s.getOpis());
        spinBrojKreveta.setValue(s.getBrojKreveta());
    }
}
